// Code generated by me. DO NOT EDIT.

package goIdlMiop

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "MIOP::Address", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "MIOP::Address" from: "string"
type MiopAddress string

//noinspection GoSnakeCaseUsage
type MiopAddress_Helper struct {
}

//noinspection GoSnakeCaseUsage
const MiopAddressId_Const = "IDL:omg.org/MIOP/Address:1.0"

func (self MiopAddress_Helper) Id() string {
	return MiopAddressId_Const
}

func (self MiopAddress_Helper) Read(stream __goidl__.IReadAny) (string, error) {
	result, err := __goidl__.IdlStringHelper.Read(stream)
	return result, err
}

func (self MiopAddress_Helper) Write(stream __goidl__.IWriteAny, v string) error {
	return __goidl__.IdlStringHelper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var MiopAddressHelper = MiopAddress_Helper{}

func init() {
}
