// Code generated by me. DO NOT EDIT.

package goIdlMiop

import __goIdlIop__ "github.com/bhbosman/goIdlIop"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "MIOP::UIPMC_ProfileBody", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type MiopUipmcProfileBody struct {
	__goidl__.IdlObject
	MiopVersion MiopVersion `json:"MiopVersion"`
	TheAddress string `json:"TheAddress"`
	ThePort int16 `json:"ThePort"`
	Components __goIdlIop__.IopTaggedComponentSeq `json:"Components"`
}

//noinspection GoSnakeCaseUsage
const MiopUipmcProfileBodyId_Const = "IDL:omg.org/MIOP/UIPMC_ProfileBody:1.0"

func (self *MiopUipmcProfileBody) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *MiopUipmcProfileBody) GoString() string {
	return self.String()
}

func (self *MiopUipmcProfileBody) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.MiopVersion.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.TheAddress, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(ShortType)
	self.ThePort, err = __goidl__.IdlInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Components.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopUipmcProfileBody) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopUipmcProfileBody) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.MiopVersion.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.TheAddress)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(ShortType)
	err = __goidl__.IdlInt16Helper.Write(stream, self.ThePort)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Components.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type MiopUipmcProfileBody_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var MiopUipmcProfileBodyHelper = MiopUipmcProfileBody_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			MiopUipmcProfileBodyId_Const,
			__goidl__.StructType,
			"MIOP.idl",
			"xdl_MiopUipmcProfileBody.go",
			func() __goidl__.IIdlObject {
				return &MiopUipmcProfileBody{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &MiopUipmcProfileBody{}
			},
			__reflect__.TypeOf((*MiopUipmcProfileBody)(nil))))
}
