// Code generated by me. DO NOT EDIT.

package goIdlMiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "MIOP::PacketHeader_1_0", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type MiopPacketHeader10 struct {
	__goidl__.IdlObject
	Magic [4]byte `json:"Magic"`
	HdrVersion byte `json:"HdrVersion"`
	Flags byte `json:"Flags"`
	PacketLength uint16 `json:"PacketLength"`
	PacketNumber uint32 `json:"PacketNumber"`
	NumberOfPackets uint32 `json:"NumberOfPackets"`
	Id MiopUniqueId `json:"Id"`
}

//noinspection GoSnakeCaseUsage
const MiopPacketHeader10Id_Const = "IDL:omg.org/MIOP/PacketHeader_1_0:1.0"

func (self *MiopPacketHeader10) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *MiopPacketHeader10) GoString() string {
	return self.String()
}

func (self *MiopPacketHeader10) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(CharType)
	for i0 := 0; i0 < 4; i0++ {
		self.Magic[i0], err = __goidl__.IdlOctetHelper.Read(stream)
		if err != nil {
			return err
		}
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.HdrVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.Flags, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedShortType)
	self.PacketLength, err = __goidl__.IdlUInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.PacketNumber, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.NumberOfPackets, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Id.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopPacketHeader10) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopPacketHeader10) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(CharType)
	for i0 := 0; i0 < 4; i0++ {
		err = __goidl__.IdlOctetHelper.Write(stream, self.Magic[i0])
		if err != nil {
			return err
		}
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.HdrVersion)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.Flags)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedShortType)
	err = __goidl__.IdlUInt16Helper.Write(stream, self.PacketLength)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.PacketNumber)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.NumberOfPackets)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Id.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type MiopPacketHeader10_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var MiopPacketHeader10Helper = MiopPacketHeader10_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			MiopPacketHeader10Id_Const,
			__goidl__.StructType,
			"MIOP.idl",
			"xdl_MiopPacketHeader10.go",
			func() __goidl__.IIdlObject {
				return &MiopPacketHeader10{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &MiopPacketHeader10{}
			},
			__reflect__.TypeOf((*MiopPacketHeader10)(nil))))
}
