// Code generated by me. DO NOT EDIT.

package goIdlMiop

import __goIdlGiop__ "github.com/bhbosman/goIdlGiop"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "MIOP::Version", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type MiopVersion struct {
	__goIdlGiop__.GiopVersion
}

//noinspection GoSnakeCaseUsage
const MiopVersionId_Const = "IDL:MIOP/Version:1.0"

func (self *MiopVersion) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *MiopVersion) GoString() string {
	return self.String()
}

func (self *MiopVersion) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopVersion.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopVersion) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopVersion) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopVersion.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type MiopVersion_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var MiopVersionHelper = MiopVersion_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			MiopVersionId_Const,
			__goidl__.StructType,
			"MIOP.idl",
			"xdl_MiopVersion.go",
			func() __goidl__.IIdlObject {
				return &MiopVersion{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &MiopVersion{}
			},
			__reflect__.TypeOf((*MiopVersion)(nil))))
}
