// Code generated by me. DO NOT EDIT.

package goIdlMiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "MIOP::UniqueId", generatedBy by: "WriteStructSequenceDcl"
type MiopUniqueId struct {
	__goidl__.IdlObject
	Array []byte `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const MiopUniqueIdId_Const = "IDL:MIOP/UniqueId:1.0"

func (self *MiopUniqueId) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *MiopUniqueId) GoString() string {
	return self.String()
}

func (self *MiopUniqueId) ReadValue(stream __goidl__.IReadAny) error {
	err := self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	var n uint32
	n, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	if n > 0 {
		self.Array = make([]byte, n)
		var i uint32
		for i = 0; i < n; i++ {
			self.Array[i], err = __goidl__.IdlOctetHelper.Read(stream)
				if err != nil {
				return err
			}
		}
	}
	return nil
}

func (self *MiopUniqueId) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *MiopUniqueId) Write(stream __goidl__.IWriteAny) error {
	err := self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	err = __goidl__.IdlUInt32Helper.Write(stream, uint32(len(self.Array)))
	if err != nil {
	return err
	}
	if len(self.Array) > 0 {
		for _, item := range self.Array {
			err = __goidl__.IdlOctetHelper.Write(stream, item)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type MiopUniqueId_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var MiopUniqueIdHelper = MiopUniqueId_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			MiopUniqueIdId_Const,
			__goidl__.SequenceType,
			"MIOP.idl",
			"xdl_MiopUniqueId.go",
			func() __goidl__.IIdlObject {
				return &MiopUniqueId{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &MiopUniqueId{}
			},
			__reflect__.TypeOf((*MiopUniqueId)(nil))))
}
